# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aiko' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aiko
  pod 'GoogleSignIn'

  target 'Aiko-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AikoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Aiko-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!ø

end
